apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: {{ .Values.istio.namespace }}
spec:
  interval: {{ .Values.reconciliation.interval }}
  chart:
    spec:
      chart: base
      version: {{ .Values.istio.version }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.istio.repository.name }}
        namespace: {{ .Values.istio.namespace }}
      interval: {{ .Values.chart.interval }}
  values:
    defaultRevision: {{ .Values.istio.revision.default }}
