apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: {{ .Values.istio.namespace }}
spec:
  interval: {{ .Values.reconciliation.interval }}
  dependsOn:
    - name: istio-base
      namespace: {{ .Values.istio.namespace }}
  chart:
    spec:
      chart: istiod
      version: {{ .Values.istio.version }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.istio.repository.name }}
        namespace: {{ .Values.istio.namespace }}
      interval: {{ .Values.chart.interval }}
