apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.httpbin2.instance2.name }}
  namespace: {{ .Values.httpbin2.instance2.namespace }}
  labels:
    app: {{ .Values.httpbin2.instance2.name }}
spec:
  selector:
    app: {{ .Values.httpbin2.instance2.name }}
  ports:
    - name: http
      port: {{ .Values.httpbin2.servicePort }}
      targetPort: {{ .Values.httpbin2.port }}
