apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.httpbin2.instance1.name }}
  namespace: {{ .Values.httpbin2.instance1.namespace }}
spec:
  selector:
    app: {{ .Values.httpbin2.instance1.name }}
  ports:
    - name: http
      port: {{ .Values.httpbin2.servicePort }}
      targetPort: {{ .Values.httpbin2.port }}
