apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.httpbin2.instance3.name }}
  namespace: {{ .Values.httpbin2.instance3.namespace }}
spec:
  replicas: {{ .Values.httpbin2.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.httpbin2.instance3.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.httpbin2.instance3.name }}
    spec:
      containers:
        - name: {{ .Values.httpbin2.instance3.name }}
          image: "{{ .Values.httpbin2.image.repo }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.httpbin2.imagePullPolicy }}
          args:
            - "/httpbin2"
            - "--message-hostname"
            - "--message"
            - "{{ .Values.httpbin2.instance3.name }}"
            - "--port"
            - "{{ .Values.httpbin2.port }}"
          ports:
            - containerPort: {{ .Values.httpbin2.port }}
