apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.httpbin2.instance2.name }}
  namespace: {{ .Values.httpbin2.instance2.namespace }}
spec:
  replicas: {{ .Values.httpbin2.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.httpbin2.instance2.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.httpbin2.instance2.name }}
    spec:
      containers:
        - name: {{ .Values.httpbin2.instance2.name }}
          image: "{{ .Values.httpbin2.image.repo }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.httpbin2.imagePullPolicy }}
          args:
            - "/httpbin2"
            - "--message-hostname"
            - "--message"
            - "{{ .Values.httpbin2.instance2.name }}"
            - "--port"
            - "{{ .Values.httpbin2.port }}"
            - "--relay"
            - "http://{{ .Values.httpbin2.instance3.name }}"
            - "--delay-min-ms"
            - "{{ .Values.httpbin2.instance2.qos.delayMin }}"
            - "--delay-max-ms"
            - "{{ .Values.httpbin2.instance2.qos.delayMax }}"
            - "--delay-rate"
            - "{{ .Values.httpbin2.instance2.qos.delayRate }}"
            - "--status-code"
            - "{{ .Values.httpbin2.instance2.qos.statusCode }}"
            - "--status-code-rate"
            - "{{ .Values.httpbin2.instance2.qos.statusCodeRate }}"
          ports:
            - containerPort: {{ .Values.httpbin2.port }}
