apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.httpbin2.instance1.name }}
  namespace: {{ .Values.httpbin2.instance1.namespace }}
spec:
  hosts:
    - {{ .Values.httpbin2.instance1.fqdn }}
  gateways:
    - {{ .Values.httpbin2.instance1.name }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: {{ .Values.httpbin2.servicePort }}
            host: {{ .Values.httpbin2.instance1.name }}
